### ISSUE TITLE
TypeError: 'method' object is not subscriptable on running download_data.sh

### ISSUE THREAD

**Issue by dapurv5** [google-research/xtreme#63]
I see the following error when I run the 

scripts/download_data.sh

```
Traceback (most recent call last):
  File "/home/ec2-user/xtreme/third_party/ud-conversion-tools/conllu_to_conll.py", line 53, in <module>
    main()
  File "/home/ec2-user/xtreme/third_party/ud-conversion-tools/conllu_to_conll.py", line 41, in main
    orig_treebank = cio.read_conll_u(args.input)#, args.keep_fused_forms, args.lang, POSRANKPRECEDENCEDICT)
  File "/home/ec2-user/xtreme/third_party/ud-conversion-tools/lib/conll.py", line 382, in read_conll_u
    sent.nodes[token_dict['id']].update({k: v for (k, v) in token_dict.items()
TypeError: 'method' object is not subscriptable
```

**Comment by XmainX** [comment]
Hi, i solved this error following:
1. making sure your `networkx` package's version is 1.11 on the xtreme environment
2. replacing all '**nodes[**' by '**node[**' in the file 

> xtreme\third_party\ud-conversion-tools\lib\conll.py


3. running after activating the xtreme environment

`networkx.DiGraph.nodes` looks like a function and you may need to get the dictionary using `networkx.DiGraph.node`
