### ISSUE TITLE
Tatoeba dataset download fails with scripts/download_data.sh

### ISSUE THREAD

**Issue by konstantinjdobler** [google-research/xtreme#79]
The download of the Tatoeba dataset fails when running `bash scripts/download_data.sh` with the following output:
```sh
--2021-11-20 14:02:31--  https://github.com/facebookresearch/LASER/archive/master.zip
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2021-11-20 14:04:32--  (try: 2)  https://github.com/facebookresearch/LASER/archive/master.zip
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/facebookresearch/LASER/zip/master [following]
--2021-11-20 14:05:40--  https://codeload.github.com/facebookresearch/LASER/zip/master
Resolving codeload.github.com (codeload.github.com)... 20.205.243.165
Connecting to codeload.github.com (codeload.github.com)|20.205.243.165|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-11-20 14:05:41 ERROR 404: Not Found.

unzip:  cannot find or open master.zip, master.zip.zip or master.zip.ZIP.
mv: cannot stat '<redacted>/xtreme/download//tatoeba-tmp//LASER-master/data/tatoeba/v1/*': No such file or directory
Traceback (most recent call last):
  File "<redacted>/xtreme/utils_preprocess.py", line 533, in <module>
    tatoeba_preprocess(args)
  File "<redacted>/xtreme/utils_preprocess.py", line 397, in tatoeba_preprocess
    shutil.copy(src_file, src_out)
  File "/opt/conda/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '<redacted>/xtreme/download//tatoeba-tmp//tatoeba.afr-eng.afr'
```

**Comment by fe1ixxu** [comment]
Same issue here

**Comment by sebastianruder** [comment]
Looks great. Thanks so much.

**Comment by sebastianruder** [comment]
https://github.com/google-research/xtreme/pull/80 addresses this. Thanks, @konstantinjdobler.
